apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: "cloudflare/cloudflared:2022.11.0"
          imagePullPolicy: IfNotPresent
          args:
            - tunnel
            - --loglevel
            - debug
            - --transport-loglevel
            - debug
            - --protocol
            - quic
            - run
            - --token
            - eyJhIjoiODFjMjdhYThiZWMwOTQyZjFlZDY0YjdkNzQwMjVjOGYiLCJ0IjoiYWU2ZDhiMDUtNGQ2OS00ZDI3LWI4YTktNDU2NTU4NzQyYTAxIiwicyI6Ik16QmxOekV4TnpndE1HUm1aUzAwTjJZM0xXSmpNV0l0WVRCaU56QmlOekZtWldFdyJ9
          volumeMounts:
          - name: config
            mountPath: /etc/cloudflared/
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflared
          items:
          - key: config.yaml
            path: config.yaml
