apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: scw-secret-store
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: "9c3369b0-7bf1-4453-a56a-1e5c7ff0fa97"
      accessKey:
        secretRef:
          namespace: external-secrets
          name: scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          namespace: external-secrets
          name: scwsm-secret
          key: secret-key

  conditions:
    - namespaceSelector:
        matchLabels:
          secret.htoh.io/required: "true"
    - namespaces:
      - "cert-manager"