apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opentelemetry-collector
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: scw-secret-store
    kind: ClusterSecretStore
  target:
    name: opentelemetry-collector
  data:
    - secretKey: prometheus-endpoint
      remoteRef:
        key: id:68bc5c22-ab3a-4c21-83c0-cbdebceeb3c2
        version: latest_enabled
    - secretKey: loki-endpoint
      remoteRef:
        key: id:20788b9f-6cd5-49a9-81d3-dcb3532b7e24
        version: latest_enabled
