apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opentelemetry-collector
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: scw-secret-store
    kind: ClusterSecretStore
  target:
    name: opentelemetry-collector
  data:
    - secretKey: grafana-cloud-secret-key
      remoteRef:
        key: id:a4759563-7e68-4bab-bd00-004f9568599c
        version: latest_enabled
