apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-credential
spec:
  refreshInterval: 60m

  secretStoreRef:
    name: scw-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .registrycredential | toString }}"
    name: registry-credential

  data:
    - secretKey: registrycredential
      remoteRef:
        key: id:3027a652-5f50-471e-893b-7f73ec78a63e
        version: latest_enabled
