apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azuredns-config
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: scw-secret-store
    kind: ClusterSecretStore
  target:
    name: azuredns-config
  data:
    - secretKey: client-secret
      remoteRef:
        key: id:7ac3fa4e-40c4-461f-9872-76e4d25693d4
        version: latest_enabled
