apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-agent-operator
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: scw-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-agent-operator
    template:
      engineVersion: v2
      data:
        logs-instance-id: "117449"
        metrics-instance-id: "236956"
        grafana-cloud-secret-key: "{{.grafana_cloud_secret_key}}"
  data:
    - secretKey: grafana_cloud_secret_key
      remoteRef:
        key: id:a4759563-7e68-4bab-bd00-004f9568599c
        version: latest_enabled
