mode: daemonset

fullnameOverride: "open-telemetry-collector"

service:
  enabled: true

presets:
  hostMetrics:
    enabled: false
  clusterMetrics:
    enabled: false
  kubeletMetrics:
    enabled: false
  logsCollection:
    enabled: true
    includeCollectorLogs: true

config:
  receivers: 
    filelog:
      exclude:
      - /var/log/pods/open-telemetry_open-telemetry-collector*/opentelemetry-collector/*.log
      - /var/log/pods/kube-system_konnectivity-agent*/konnectivity-agent/*.log
      include:
      # - /var/log/pods/*/*/*.log
      - /var/log/pods/ingress-nginx_nginx-ingress-ingress-nginx-controller-*/*/*.log
  exporters:
    logging:
      verbosity: detailed
    #prometheusremotewrite:
    #  endpoint: ${env:PROMETHEUS_ENDPOINT}
    #loki:
    #  endpoint: https://api_key:<Token>@logs.cockpit.fr-par.scw.cloud/loki/api/v1/push
  service:
    pipelines:
      metrics: null
      traces: null
      logs:
        exporters:
          - logging