controller:
  service:
    # Enable to avoid node forwarding
    externalTrafficPolicy: "Local"
    annotations:
      service.beta.kubernetes.io/scw-loadbalancer-proxy-protocol-v2: "true"
      # Enable this annotation to use cert-manager
      service.beta.kubernetes.io/scw-loadbalancer-use-hostname: "true"
  
  config:
    allow-snippet-annotations: "true"
    proxy-buffer-size: "16k"
    client-body-buffer-size: "512k"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    # Enable proxy protocol to get client ip addr instead of loadbalancer one
    use-proxy-protocol: "true"
    proxy-add-original-uri-header: "true"
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "request_id": "$req_id", "proxy_upstream_name": "$proxy_upstream_name", "proxy_alternative_upstream_name": "$proxy_alternative_upstream_name","upstream_status": $upstream_status, "upstream_addr": "$upstream_addr","http_request":{"request_method": "$request_method", "request_uri": "$host$request_uri", "status": $status,"request_length": $request_length, "response_length": $upstream_response_length, "user_agent": "$http_user_agent", "remote_ip": "$remote_addr", "referer": "$http_referer", "latency": "$upstream_response_time s", "protocol":"$server_protocol"}}'
