name: Package Docker image 

on:
  workflow_call:
    inputs:
      app_name:
        required: true 
        type: string
      app_version:
        description: App version. If image is metabase/metabase:v0.43.4, then app_version = v0.43.4
        required: false
        type: string
    secrets:
      ACR_ENDPOINT:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
    outputs:
      version: 
        description: "Package's version"
        value: ${{ jobs.package.outputs.version }}

jobs:
  package:
    name: Package Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - id: setup_pack
        name: Setup Buildpack
        uses: buildpacks/github-actions/setup-pack@v4.4.0
      - id: release_docker
        if: ${{ inputs.app_version == null }}
        name: Release Docker image
        run: |
          image_name=${{ secrets.ACR_ENDPOINT }}/${{ inputs.app_name }}:${{ inputs.app_version }}
          pack build $image_name --builder paketobuildpacks/builder:base
          docker push $image_name
